# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mobo_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mobo_iOS
pod 'Tabman', '~> 2.6'
pod 'Pageboy', '~> 3.2'
pod 'lottie-ios'
pod 'Firebase/Analytics'
pod 'Firebase/RemoteConfig'
pod 'SnapKit', '~> 5.0.0'
pod 'TextFieldEffects'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'ObjectMapper','~>3.4'
pod 'Alamofire', '~> 4.7'
pod 'FloatRatingView', '~> 4'
pod 'Hashtags'
pod 'Kingfisher', '~> 5.0'



end
