# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mobo_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mobo_iOS
pod 'Tabman', '~> 2.6'
pod 'Pageboy', '~> 3.2'
pod 'lottie-ios'
#pod 'SnapKit','~> 3.2.0'
pod 'Firebase/Analytics'
pod 'Firebase/RemoteConfig'
pod 'SnapKit', '~> 5.0.0'
pod 'TextFieldEffects'
pod 'Firebase/Database'
pod 'Firebase/Auth'
end
